### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ErezSha** [fubhy/react-query-builder#2]
Hey,

Is the licence of this project MIT?

**Comment by fubhy** [comment]
Yes. Feel free to use it however you like. Mind you though: It's nowhere near finished. I am using a fork of it in production which has some additional non-completed features in there like validation etc. to make it usable but the version you see here is not finished. I will get back to it in a bit but not before a couple weeks from now.

**Comment by fubhy** [comment]
@ErezSha Do you still want to discuss this project? If so, I'd have time again tomorrow.
